### ISSUE TITLE
restore fails in a while

### ISSUE THREAD

**Issue by itogo** [gaubert/gmvault#207]
Hi,

I've been trying to restore recently backuped mailbox to the new one and got an error after processing a few hundreds emails:

Eugene-MacBook:bin ei$ ./gmvault restore *******@gmail.com --resume
[....]
Jun 25 23:02:02 Eugene-MacBook.local gmv_runner[30449] <Notice>: Pushing email body with id 1407299977163162301.
Jun 25 23:02:03 Eugene-MacBook.local gmv_runner[30449] <Notice>: Pushing email body with id 1407316912607036964.
Jun 25 23:02:03 Eugene-MacBook.local gmv_runner[30449] <Notice>: Applying labels to the current batch of emails.
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: Error: %d format: a number is required, not set. 
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: 
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: === Exception traceback ===
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: Traceback (most recent call last):
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>:   File "gmv/gmv_cmd.pyc", line 745, in run
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>:   File "gmv/gmv_cmd.pyc", line 621, in _restore
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>:   File "gmv/gmvault.pyc", line 882, in restore
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>:   File "gmv/gmvault.pyc", line 1146, in restore_emails
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: TypeError: %d format: a number is required, not set
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: 
Jun 25 23:02:04 Eugene-MacBook.local gmv_runner[30449] <Notice>: === End of Exception traceback ===

in debug mode:
Eugene-MacBook:bin ei$ ./gmvault restore ********@gmail.com --resume -debug
[....]
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: result_uid = 882
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: label = \Inbox
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Pushing email body with id 1407316912607036964.
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Subject = Re: news.
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Before to Append email contents
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Appended data with flags [u'\\Seen'] and internal time 2012-07-12 22:39:54. Operation time = 0.355708122253.
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: res = [APPENDUID 11 883] (Success)
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: result_uid = 883
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: label = \Inbox
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: label = \Important
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Labels creation tentative for emails with ids <itertools.ifilter object at 0x10622e390>.
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Labels to create: [set([u'\\Draft', u'\\Inbox', u'\\Sent', u'\\Important'])]
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Applying labels to the current batch of emails.
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Changing directory. Going into ALLMAIL
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Changed dir. Operation time = 0.190242052078 ms
Jun 25 23:15:58 Eugene-MacBook.local gmv_runner[30528] <Notice>: Applying labels [u'\\Draft']
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: After storing labels (\Draft). Operation time = 0.106867074966 s.
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: ret = NO
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: data=['System Error (Failure)']
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: Problem when applying labels \Draft to the following ids: set([865, 874])
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: Problem when applying labels.
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: Error: %d format: a number is required, not set. 
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: === Exception traceback ===
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: Traceback (most recent call last):
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>:   File "gmv/gmv_cmd.pyc", line 745, in run
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>:   File "gmv/gmv_cmd.pyc", line 621, in _restore
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>:   File "gmv/gmvault.pyc", line 882, in restore
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>:   File "gmv/gmvault.pyc", line 1146, in restore_emails
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: TypeError: %d format: a number is required, not set
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: 
Jun 25 23:15:59 Eugene-MacBook.local gmv_runner[30528] <Notice>: === End of Exception traceback ===

**Comment by aaronthebaron** [comment]
I'm getting a similar error in 1.9. Here's mine with a bit more debug on:
```
result_uid = 108660
label = \Draft

Labels creation tentative for emails with ids <itertools.ifilter object at 0x7f096aa2bbd0>.
Labels to create: [set([u'\\Draft', u'gmv-muted', u'Twitter', u'\\Sent', u'\\Important'])]
Applying labels to the current batch of emails.
Changing directory. Going into ALLMAIL
Changed dir. Operation time = 0.817802906036 ms
Applying labels [u'\\Draft']
After storing labels (\Draft). Operation time = 0.0935781002045 s.
ret = NO
data=['System Error (Failure)']
Problem when applying labels \Draft to the following ids: set([108660, 108621])
Problem when applying labels.
Error: %d format: a number is required, not set.

=== Exception traceback ===
Traceback (most recent call last):
  File "/root/mailback/local/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 745, in run
    self._restore(args, credential)
  File "/root/mailback/local/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 621, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/root/mailback/local/lib/python2.7/site-packages/gmv/gmvault.py", line 882, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/root/mailback/local/lib/python2.7/site-packages/gmv/gmvault.py", line 1146, in restore_emails
    raise err
TypeError: %d format: a number is required, not set

=== End of Exception traceback ===
```

**Comment by jelmok** [comment]
I have the exact same problem.  Here's the debug output.  Am using v1.9 of GMVault on Mac OS X 10.10.3(14D136).

Jul  4 21:42:47 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Pushing email body with id 1478754833575586771.
Jul  4 21:42:47 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Subject = =?UTF-8?Q?Out_of_Office_until_Monday_11/09/2014_Re:_Sterling_co?=.
Jul  4 21:42:47 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Before to Append email contents
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Appended data with flags [u'\\Seen'] and internal time 2014-09-09 09:15:04. Operation time = 0.344129085541.
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: res = [APPENDUID 11 20885] (Success)
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: 
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: result_uid = 20885
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: label = \Sent
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: 
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Labels creation tentative for emails with ids <itertools.ifilter object at 0x106c2ce90>.
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Labels to create: [set([u'INBOX/FREIGHT/D & G(TransGlobal)', u'\\Inbox', u'\\Draft', u'INBOX/Suppliers/component suppliers (local)/Thomas & Betts', u'INBOX/FX/World First', u'INBOX/HR/AccountsAssit candidates', u'INBOX/FREIGHT/DHL', u'INBOX/BANK details/HSBC Invoice Finance', u'\\Sent', u'\\Important', u'INBOX/Customers/Barnsley', u'INBOX/Insurance/Motor Vehicle', u'INBOX/Customers/Rotherham', u'INBOX/Customers/Smith Brothers', u'INBOX/Customers/East Ayreshire', u'INBOX/FREIGHT/Quotes', u'INBOX/FREIGHT/Int
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Labels to create: [set([u'INBOX/FREIGHT/D & G(TransGlobal)', u'\\Inbox', u'\\Draft', u'INBOX/Suppliers/component suppliers (local)/Thomas & Betts', u'INBOX/FX/World First', u'INBOX/HR/AccountsAssit candidates', u'INBOX/FREIGHT/DHL', u'INBOX/BANK details/HSBC Invoice Finance', u'\\Sent', u'\\Important', u'INBOX/Customers/Barnsley', u'INBOX/Insurance/Motor Vehicle', u'INBOX/Customers/Rotherham', u'INBOX/Customers/Smith Brothers', u'INBOX/Customers/East Ayreshire', u'INBOX/FREIGHT/Quotes', u'INBOX/FREIGHT/Int
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Labels to create: [set([u'INBOX/FREIGHT/D & G(TransGlobal)', u'\\Inbox', u'\\Draft', u'INBOX/Suppliers/component suppliers (local)/Thomas & Betts', u'INBOX/FX/World First', u'INBOX/HR/AccountsAssit candidates', u'INBOX/FREIGHT/DHL', u'INBOX/BANK details/HSBC Invoice Finance', u'\\Sent', u'\\Important', u'INBOX/Customers/Barnsley', u'INBOX/Insurance/Motor Vehicle', u'INBOX/Customers/Rotherham', u'INBOX/Customers/Smith Brothers', u'INBOX/Customers/East Ayreshire', u'INBOX/FREIGHT/Quotes', u'INBOX/FREIGHT/Int
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmvault.pyc, line 1134
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 622
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 642
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 651
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 622
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 642
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 651
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 622
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/imap_utils.pyc, line 642
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmvault.pyc, line 1138
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmvault.pyc, line 1139
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmv_cmd.pyc, line 786
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmv_cmd.pyc, line 787
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmv_cmd.pyc, line 788
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Traceback (most recent call last):
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 217, in handle
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 567, in emit
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>:   File "logbook/handlers.pyc", line 562, in write
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: IOError: [Errno 32] Broken pipe
Jul  4 21:42:48 Johns-MacBook-Pro.local gmv_runner[13868] <Notice>: Logged from file /Users/orangetek/Downloads/gmvault-v1.9/lib/gmv_runner.app/Contents/Resources/gmv/gmv_cmd.pyc, line 789

**Comment by gaubert** [comment]
All Ok I need to check. Give me couple of days. Thanks

**Comment by gaubert** [comment]
@aaronthebaron @itogo There was a problem in 1.9 when applying non ascii labels. I have fixed it now on 1.9.1. I could produce a test version for you. Could you make a test for me ?
It seems that you are on windows. Is it correct ?

**Comment by aaronthebaron** [comment]
I'm on Linux. I could definitely do a test, but it will be this weekend as
I'm getting on an airplane. Thanks!

**Comment by gaubert** [comment]
@aaronthebaron On Linux please pull v1.9.1and test it. For me it working now. Let me know. Thanks

**Comment by LelandTheG** [comment]
I have the same issue on 1.9, is there a work around for now? I need to restore a users gmail and its cutting off about 5 months of restore at the point of error.

**Comment by aaronthebaron** [comment]
@gaubert It seems like it's still failing for me in the same place. Is there a way I can peel off the message for use as a test case for you?

**Comment by gaubert** [comment]
@aaronthebaron Please send me output of your console once you have added --debug in your commandline. You could also pull v1.9.1 and try with that version. I believe this has been solved. Could you do that to help me ? Or I could send you a beta version of 1.9.1 if you are on a mac or windows machine. Let me know

**Comment by aaronthebaron** [comment]
@gaubert It's the same as before, but let me give you my steps first.

1. I pulled the gmv-1.9.1 branch
2. python setup.py install inside of a new virtualenv.
3. I ran this command: gmvault restore -d ~/gmvault-db [email redacted] --resume --debug


Here's the output:
Pushing email body with id 1449255964275765650.
Subject = Pivotal Stories for Dave and Tim.
Before to Append email contents
Appended data with flags [u'\\Seen'] and internal time 2013-10-18 13:43:10. Operation time = 0.24090886116.
res = [APPENDUID 11 109060] (Success)

result_uid = 109060
label = \Draft

Labels creation tentative for emails with ids <itertools.ifilter object at 0x7f0c0204e950>.
Labels to create: [set([u'\\Draft', u'gmv-muted', u'Twitter', u'\\Sent', u'\\Important'])]
Applying labels to the current batch of emails.
Changing directory. Going into ALLMAIL
Changed dir. Operation time = 0.655024051666 ms
Applying labels [u'\\Draft']
After storing labels (\Draft). Operation time = 0.0857520103455 s.
ret = NO
data=['System Error (Failure)']
Problem when applying labels \Draft to the following ids: set([109060, 109021])
Problem when applying labels.
Error: %d format: a number is required, not set.

=== Exception traceback ===
Traceback (most recent call last):
  File "/root/mailback-1.9.1/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 750, in run
    self._restore(args, credential)
  File "/root/mailback-1.9.1/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/gmv_cmd.py", line 625, in _restore
    emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/root/mailback-1.9.1/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 900, in restore
    self.restore_emails(pivot_dir, extra_labels, restart)
  File "/root/mailback-1.9.1/local/lib/python2.7/site-packages/gmvault-1.9.1-py2.7.egg/gmv/gmvault.py", line 1164, in restore_emails
    raise err
TypeError: %d format: a number is required, not set

=== End of Exception traceback ===

**Comment by gaubert** [comment]
@aaronthebaron There was a forgotten possible error case. I has been fixed now. Please pull again, try and let know.

Thanks

**Comment by aaronthebaron** [comment]
You got it, it's working. Thanks!

**Comment by gaubert** [comment]
@aaronthebaron Great ! Thanks for the testing.

**Comment by gaubert** [comment]
close it now

**Comment by gunerharun** [comment]
@gaubert I think I am having the same problem. I'm on a Mac. Would you be able to send me the beta version for mac?  Thank you

**Comment by gaubert** [comment]
yes please try that one and let me know:
https://www.dropbox.com/s/oqxlqmghs0pgydw/gmvault-v1.9.1-macosx-intel.tar.gz?dl=0

Thks

**Comment by gunerharun** [comment]
Hello Guillaume,

Thank you very much for your email. I just updated to the beta and ran the
software. Unfortunately it got stuck in the same place. Here is where it
got stuck. Do you have an idea why it might be?

Best,

Harun

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Before
to Append email contents

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
Appended data with flags [u'\\Seen'] and internal time 2010-12-15 20:55:20.
Operation time = 0.611764907837.

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: res =
[APPENDUID 11 2512] (Success)

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
result_uid = 2512

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: label =
\Sent

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Labels
creation tentative for emails with ids <itertools.ifilter object at
0x10618ec10>.

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Labels
to create: [set([u'\\Draft', u'\\Inbox', u'\\Sent'])]

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
Applying labels to the current batch of emails.

Sep 13 22:47:31 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
Changing directory. Going into ALLMAIL

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Changed
dir. Operation time = 0.194859981537 ms

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
Applying labels [u'\\Draft']

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: After
storing labels (\Draft). Operation time = 0.218069076538 s.

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: ret = NO

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
data=['System Error (Failure)']

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Problem
when applying labels \Draft to the following ids: set([2508, 2509])

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Problem
when applying labels.

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: Error:
%d format: a number is required, not set.

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: ===
Exception traceback ===

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
Traceback (most recent call last):

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:   File
"gmv/gmv_cmd.pyc", line 745, in run

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:   File
"gmv/gmv_cmd.pyc", line 621, in _restore

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:   File
"gmv/gmvault.pyc", line 882, in restore

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:   File
"gmv/gmvault.pyc", line 1146, in restore_emails

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:
TypeError: %d format: a number is required, not set

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>: === End
of Exception traceback ===

Sep 13 22:47:32 Haruns-MacBook-Air.local gmv_runner[8078] <Notice>:

**Comment by gaubert** [comment]
@gunerharun Are you sure you used the beta version because normally the outputs should be much clearer ? Could you double check and re-run it completly with --debug activated and send me the logs because I thought to have covered those issues.
Thanks

**Comment by gunerharun** [comment]
You are right. I was in the wrong folder,so I ran the old version again.
Now it got past the place it got stuck before.

Thank you very much,
Harun

On Mon, Sep 14, 2015 at 11:36 AM, Guillaume Aubert <notifications@github.com

**Comment by gaubert** [comment]
Great, that's a relief. Thanks for the testing.

**Comment by gunerharun** [comment]
It's a pleasure. Take care

On Mon, Sep 14, 2015 at 10:59 PM, Guillaume Aubert <notifications@github.com
